[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_THEME = "jane"
  HUGO_BASEURL = "/"

[context.production.environment]
  HUGO_VERSION = "0.73.3"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.65.0"
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.74.3"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"
