name: Publish via FTP

on:
  push:
    branches:
    - master
  # schedule:
  #   - cron:  '0 8 * * *'

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1
      with:
        submodules: false

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.123.8'
        extended: 'true'

    - name: Build
      run: hugo -D --minify

    - name: Deploy to FTP
      uses: airvzxf/ftp-deployment-action@latest
      with:
        server: ngcobalt387.manitu.net
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local_dir: "./public"
