name: Publish via FTP

on:
  push:
    branches:
    - master
  # schedule:
  #   - cron:  '0 8 * * *'

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1
      with:
        submodules: false

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.100.2'
        extended: 'true'

    - name: Build
      run: hugo -D --minify

    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.4
      with:
        server: ngcobalt387.manitu.net
        port: 21
        protocol: ftps
        # server-dir: .
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: public/
